Models/ErrorViewModel.cs
namespace Portfolio.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/User.cs
namespace Portfolio.Models;

public class User
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Age { get; set; }
}

Controllers/DataBaseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Portfolio.Controllers;

public class DataBaseController : Controller
{
    private readonly ApplicationContext _db;

    public DataBaseController(ApplicationContext db)
    {
        _db = db;
    }
}

Controllers/EmailSenderController.cs
using Microsoft.AspNetCore.Mvc;
using Portfolio.Misc;
using Portfolio.Models;

namespace Portfolio.Controllers;

public class EmailSenderController : Controller
{

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Contact()
    {
        return View();
    }

    private readonly IEmailSender _emailSender;
    private readonly EmailConfiguration _emailConfig;

    public EmailSenderController(IEmailSender emailSender, EmailConfiguration emailConfig)
    {
        _emailSender = emailSender;
        _emailConfig = emailConfig;
    }
    [HttpPost]
    public IActionResult SendEmail(
        string nameContact, 
        string emailContact, 
        string subjectContact, 
        string messageContact)
    {
        var message = new Message(new[] {_emailConfig.From}, $"Contact form: {subjectContact}",
            $"Name: {nameContact}\nEmail: {emailContact}\n\n{messageContact}");
        _emailSender.SendEmailAsync(message);

        return Ok("sent successfully");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Portfolio.Models;

namespace Portfolio.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Major()
    {
        return View();
    }

    public IActionResult Contact()
    {
        return View();
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

Views/EmailSender/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/Contact.cshtml
@{
    Layout = "_MajorLayout";
}

<div class="contact-me">
	<div class="contact-me-h3">
		<h3>CONTACT ME</h3>
	</div>
	<div class="contact-me-hr">
		<hr/>
	</div>
	<div class="contact-me-p">
		<p>It is a long established fact that a reader will be distracted by the <br>
			readable content of a 
			page when looking at its layout.
		</p>
	</div>
</div>
<div class="fields">
	<div class="form">
		<form asp-controller="EmailSender" asp-action="SendEmail" method="post">
			<div class="your-name">
				<input type="name" name="name" placeholder="   Your Name">
			</div>
			<div class="your-email">
				<input type="email" name="email" placeholder="   Your Email">
			</div>
			<div class="subject">
				<input type="text" name="subject" placeholder="   Subject">
			</div>
			<div class="your-message">
				<textarea name="message" placeholder=" Your Message" rows="5">
					</textarea>
			</div>
			<div class="submit">
				<button type="submit" name="submit" class="submit-button">Send Message</button> 
			</div>
		</form>
	</div>
</div>

Views/Home/Major.cshtml
@{
    Layout = "_MajorLayout";
}

<div class="hi">
    <div class="hi-img">
        <img src="https://templatemag.com/demo/templates/Stanley/img/user.png">
    </div>
    <div class="hi-h1">
        <h1>Hi, I am Stanley!</h1>
    </div>
    <div class="hi-p1">
        <p>Hello everybody. I'm Stanley, a free handsome bootstrap theme coded. A really simple theme <br>
            for those wanting to showcase their work with a cute & clean style.</p>
        <br>
    </div>
    <div class="hi-p2">
        <p>Please, consider to register to <a href="">our newsletter</a> to be updated with our latest themes and <br> freebies. Like always, you can use this theme in any project freely. Share it with your friends.</p>
    </div>
</div>
<div class="images">
    <div class="top-images">
        <a href="">
            <img src="https://templatemag.com/demo/templates/Stanley/img/portfolio/port01.jpg" id="left-top-img">
        </a>
        <a href="">
            <img src="https://templatemag.com/demo/templates/Stanley/img/portfolio/port02.jpg" id="center-top-img">
        </a>
        <a href="">
            <img src="https://templatemag.com/demo/templates/Stanley/img/portfolio/port03.jpg" id="right-top-img">
        </a>
    </div>
    <div class="top-images-labels">
        <ul id="top-labels">
            <li id="ape">APE</li>
            <li id="raiders">RAIDERS</li>
            <li id="vikings">VIKINGS</li>
        </ul>
    </div>
    <div class="down-images">
        <a href="">
            <img src="https://templatemag.com/demo/templates/Stanley/img/portfolio/port04.jpg" id="left-down-img">
        </a>
        <a href="">
            <img src="https://templatemag.com/demo/templates/Stanley/img/portfolio/port05.jpg" id="center-down-img">
        </a>
        <a href="">
            <img src="https://templatemag.com/demo/templates/Stanley/img/portfolio/port06.jpg" id="right-down-img">
        </a>
    </div>
    <div class="down-images-labels">
        <ul id="down-labels">
            <li id="yoda">YODA</li>
            <li id="emperors">EMPERORS</li>
            <li id="chiefs">CHIEFS</li>
        </ul>
    </div>
</div>

Views/Shared/_FooterPartialView.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - Portfolio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

Views/Shared/_HeaderPartialView.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Portfolio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Portfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Portfolio.styles.css" asp-append-version="true"/>
</head>
<body>
    @await Html.PartialAsync("_HeaderPartialView");
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
    @await Html.PartialAsync("_FooterPartialView");
</body>
</html>

Views/Shared/_MajorLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Test</title>
	<link rel="stylesheet" type="text/css" href="~/css/major.css">
	<link rel="stylesheet" type="text/css" href="~/css/contact.css"/>
</head>
<body>
	<header>
		<nav class="container">
			<a href="" class="logo">
				<span>STANLEY</span>
			</a>
			<ul id="menu">
				<li><a href="">WORK</a></li>
				<li><a href="">ABOUT</a></li>
				<li><a href="">BLOG</a></li>
				<li><a href="">CONTACT</a></li>
			</ul>
		</nav>
	</header>
	@RenderBody()
	<footer>
		<div class="top-footer">
			<div class="top-footer-elems">
				<div class="my-bunker">
					<h4>MY BUNKER</h4>
					<p>Some Address 987,</p>
					<p>+34 9054 5455</p>
					<p>Madrid, Spain</p>
				</div>
				<div class="about-stanley">
					<h4>ABOUT STANLEY</h4>
					<p>This cute them was created to showcase</p>
					<p>your work in a simple way. Use it wisely.</p>
				</div>
				<div class="my-links">
					<h4>MY LINKS</h4>
					<p><a href="">Dribbble</a></p>
					<p><a href="">Twitter</a></p>
					<p><a href="">Facebook</a></p>
				</div>
			</div>
		</div>
		<div class="down-footer">
			<div class="copyright">
				<p id="copyright">© Copyrights <span>Stanley</span>. All Rights Reserved</p>
				<p>Created with Stanley template by <a>TemplateMag</a></p>
			</div>
		</div>
	</footer>
</body>
</html>